### PR TITLE
Refactored AzureAPI

### PR DESCRIPTION
**Pull request by MercenaryJosh**

### CODE REVIEW

**Comment by wking** [comment]
The thrust here looks great :).  I left quite a few comments on the
individual commits, mostly calling for minor cleanups to the
individual commits.  There are also a few areas where we're not quite
on the same page (e.g. camelCase, but I'm fine punting there until we
get a tool to tell us what to do ;).  I'd recommend a reroll
addressing all non-controversial changes (I'm happy to help with this,
feel free to ping me for a Hangout and we can talk over any rebase
issues), and a post here summarizing the reroll's changes that lists
which comments you didn't address in that reroll and why.  I expect
the first reroll will clear up most of the issues and we'll have a lot
less to talk about for v2 ;).

**Comment by MercenaryJosh** [comment]
I addressed all of the formatting changes. Feel free to squash commits and merge as you see fit.

**Comment by wking** [comment]
On Thu, Sep 17, 2015 at 06:53:50AM -0700, MercenaryJosh wrote:
> I addressed all of the formatting changes.

Thanks :).

> Feel free to squash commits and merge as you see fit.

Working through this now…

**Comment by wking** [comment]
The Algolia stuff (independent of the loop unrolling) landed in #12.  I'm closing this, because it seems like interest in the AzureAPI-model-loop unrolling is waning, but I'm happy to have tk/refactor (currently tipped at 99d1c2c42f7a37d4d083784759a2ab5100d85d4f) picked back up and merged in if we end up deciding to unroll the loop after all.

**Pull request closed without merging**
