### PR TITLE
add pickup model for backhauls

### PR DESCRIPTION
**Pull request by MercenaryJosh**

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Jan 13, 2016 at 10:15:59PM -0800, MercenaryJosh wrote:
>   * add pickup model for backhauls

This blocking on something like azurestandard/api-spec#49 landing, no?
Otherwise I don't think we declare a pickup API.

**Comment by MercenaryJosh** [comment]
The pickup api is currently in master.

https://github.com/azurestandard/beehive/blob/master/apps/api/urls.py#L88

**Comment by wking** [comment]
On Fri, Jan 15, 2016 at 01:47:15PM -0800, MercenaryJosh wrote:
> The pickup api is currently in master.

It looks like the current API landed via mt/backhaulpickup-api with
azurestandard/beehive@fd1028b without a pull request [1], but that we
forgot to document it.  I'll file an api-spec PR
(azurestandard/api-spec#49 documents the backend after
azurestandard/beehive#1308 lands).

[1]: https://azurestandard.slack.com/archives/general/p1447093457000445

**Comment by wking** [comment]
On Fri, Jan 15, 2016 at 02:01:15PM -0800, W. Trevor King wrote:
> I'll file an api-spec PR (azurestandard/api-spec#49 documents the
> backend after azurestandard/beehive#1308 lands).

I took another look at it, and decided that azurestandard/api-spec#49
was where I ended up after trying to document
azurestandard/beehive@fd1028b back in October.  So I've thrown in the
towel on documenting the currently-live pickup API, and will just hope
we get azurestandard/api-spec#49 and azurestandard/beehive#1308 landed
soonish ;).

**Pull request merged**
