### PR TITLE
Remove deprecated services.

### PR DESCRIPTION
**Pull request by davidmcatee-azure**
The services being removed are no longer used.

### CODE REVIEW

**Comment by wking** [comment]
Can you drop these from the README as well and keep the trailing newline at the end of `azure-providers.js`?

I think it would make sense to keep these UI-agnostic services here in case we end up needing them for internal-website or some such, but we can always drag them back out of the Git history or port the analogous service over from the website repo if we end up needing them in other repositories.  There's certainly not much sense in maintaining parallel UI-agnostic services in both this repo and the website repo.

**Comment by davidmcatee-azure** [comment]
I think if this repo had just been `AzureAPI` it would have been more faithful to the single responsibility principle. In my opinion, based on my experience working on the website, the other services are doing too much for them to be very useful for a variety of use cases.  I ended up refactoring the ones I removed here into three separate layers in website (data, services, and views).

`AzureCategory` and `AzureProduct` have the same problem but perhaps to a lesser degree. In an ideal world I would move them out of here, but they are so heavily used in both website and internal-website that I don't think it's worth the attempt at this juncture.  Using them in website, while not as clean as I would like, has not been as problematic as the others proved to be.

**Comment by wking** [comment]
On Mon, Oct 17, 2016 at 11:58:50AM -0700, David McAtee wrote:
> I ended up refactoring the ones I removed here into three separate
> layers in website (data, services, and views).

I expect “views” is probably fairly UI-specific.  I'm not sure about
data and services.  Are they also UI specific?

**Comment by davidmcatee-azure** [comment]
> I expect “views” is probably fairly UI-specific.  I'm not sure about
> data and services.  Are they also UI specific?

Conceptually they are application-agnostic, even views (`viewService` just helps you create customized view objects by putting pieces of data together based on options passed in&mdash;almost like a frontend GraphQL).

But the implementation turns out to be somewhat application-specific because the code exposes particular sets of data, with convenient names, that the application is interested in (and that other applications might not be interested in).  For example, `orderData.getShippedOrders` basically wraps `AzureAPI.order.query({ 'filter-person': userId, status: 'shipped' })` and caches the results.  A different application that doesn't care about shipped orders wouldn't need that, so if the data layer was meant to be shared by different applications then each application would inevitably suffer from being forced to include some dead code.  Even `AzureAPI` has this problem to a certain degree. The website doesn't care about the `audit-product` model, but it includes [a decent amount of code related to it](https://github.com/azurestandard/azure-angular-providers/blob/master/azure-providers.js#L235-L264) that will never be used, due to the sharing of `AzureAPI`.

There are also decisions about caching in the data layer that are arguably application-specific. So it wouldn't be as easy as moving services directly from website over to here, unfortunately. But, using the website services as a starting point for refactoring things like caching and the frontend GraphQL-like functionality into more abstract and application-agnostic services is certainly possible, if that ever became a need for us.

**Comment by davidmcatee-azure** [comment]
I this ready to merge?  It would be nice to reduce the size of the website's deployed vendor.js file.

**Pull request merged**
